AWS_REGION = ''
AWS_ACCESS_KEY_ID = ''
AWS_ACCESS_SECRET_KEY = ''

CHATGPT_API_TOKEN = ''

SNS_ARN_BUDDYGUIDER_REQUEST_SUGGESTION = ''
SQS_URL_BUDDYGUIDER_REQUEST_SUGGESTION = ''

GOOGLE_API_KEY = ''
TRIPADVISOR_API_KEY = ''


ENCRYPTION_CLIENT_KEY = ""
ENCRYPTION_SERVER_KEY = ""
